# C/C++ with GCC
# Build your C/C++ project with GCC using make.
# Add steps that publish test results, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/c-cpp/gcc

trigger:
- master

strategy:
  matrix:
    linux:
      imageName: 'ubuntu-16.04'
    mac:
      imageName: 'macos-10.13'
    windows:
      imageName: 'vs2017-win2016'

pool:
  vmImage: $(imageName)

steps:
- script: |
    if [[ "$AGENT_OS" != "windows" ]]; then make config=coverage test; fi
    if [[ "$AGENT_OS" != "windows" ]]; then make config=sanitize test; fi
    if [[ "$AGENT_OS" != "windows" ]]; then make config=release test; fi
    if [[ "$AGENT_OS" == "windows" ]]; then cmake -G "Visual Studio 15 2017" -DBUILD_DEMO=ON; fi
    if [[ "$AGENT_OS" == "windows" ]]; then cmake --build . -- -property:Configuration=Debug -verbosity:minimal; fi
    if [[ "$AGENT_OS" == "windows" ]]; then ./Debug/demo.exe demo/pirate.obj; fi
    if [[ "$AGENT_OS" == "windows" ]]; then cmake --build . -- -property:Configuration=Release -verbosity:minimal; fi
    if [[ "$AGENT_OS" == "windows" ]]; then ./Release/demo.exe demo/pirate.obj; fi
    if [[ "$AGENT_OS" == "osx" ]]; then make config=iphone; fi
    if [[ "$AGENT_OS" != "windows" ]]; then bash <(curl -s https://codecov.io/bash); fi
  displayName: 'make'
